In [32]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [33]:
A=np.array([[1+2, 5+1], [2*1, 5+2]])
print(A)

[[3 6]
 [2 7]]


In [34]:
# Finding shape
shape=np.shape(A)
print(shape)

# Finding Determinant
det_a=np.linalg.det(A)
print(det_a)

# Finding Inverse when Det>0
if det_a!=0:
  inv_matrix=np.linalg.inv(A)
else:
  inv_matrix="Impossible"

print(inv_matrix)

# Finding Rank
rank=np.linalg.matrix_rank(A)
print(rank)

# Eigenvalues
eigenvalues=np.linalg.eig(A)
print(eigenvalues)



(2, 2)
9.000000000000002
[[ 0.77777778 -0.66666667]
 [-0.22222222  0.33333333]]
2
EigResult(eigenvalues=array([1., 9.]), eigenvectors=array([[-0.9486833 , -0.70710678],
       [ 0.31622777, -0.70710678]]))


In [35]:
B=np.array([[1+2, 5+1], [2*1, 5+3]])
# New value is now at (2,2) position
print(B)

[[3 6]
 [2 8]]


In [36]:
# Finding shape
shape=np.shape(B)
print(shape)

# Finding Determinant
det_b=np.linalg.det(B)
print(det_b)

# Finding Inverse when Det>0
if det_b!=0:
  inv_matrix=np.linalg.inv(B)
else:
  inv_matrix="Impossible"

print(inv_matrix)

# Finding Rank
rank=np.linalg.matrix_rank(B)
print(rank)

# Eigenvalues
eigenvalues=np.linalg.eig(B)
print(eigenvalues)

(2, 2)
12.0
[[ 0.66666667 -0.5       ]
 [-0.16666667  0.25      ]]
2
EigResult(eigenvalues=array([1.22799813, 9.77200187]), eigenvectors=array([[-0.95904921, -0.66315547],
       [ 0.2832395 , -0.74848168]]))


In [36]:
# Answer -> 01
# It changes because altering any matrix entry directly affects the determinant calculation.
# Changing a diagonal value has the most impact since det = product of eigenvalues.

# Answer -> 02
# Rank only changes if a row becomes linearly dependent on another.
# Since det ≠ 0, rank stays full.

# Answer -> 03
# They shift — the sum of eigenvalues always equals the trace.
# So, Changing a diagonal entry directly shifts the eigenvalue sum by the same amount.

# Answer -> 04
# B is easier to invert because its determinant (12) is larger than A's (9).
# The meaning it's further from singularity and more numerically stable.
# The only change was (2,2): 7→8, which directly increased the determinant by 3.
