In [1]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
# Task 1 -> Create two 3×3 matrices with random integers.

R = np.random.randint(20,30,(3, 3))
K = np.random.randint(30,40,(3,3))

# Task 2 -> Perform addition, subtraction, and multiplication operations on these matrices.

A=R+K
S=R-K
M=np.dot(R,K)

# Print all values

print(A)
print(S)
print(M)


# Task 3 -> Compute the determinant, inverse, and rank of one of the matrices.

det_R = np.linalg.det(R)

if det_R!=0:
    inv_R = np.linalg.inv(R)
else:
    inv_R = "Matrix is singular, cannot compute inverse"

rank_R = np.linalg.matrix_rank(R)

print(det_R)
print(inv_R)
print(rank_R)


[[58 54 54]
 [64 63 61]
 [51 53 51]]
[[-18 -12 -10]
 [-10 -15  -5]
 [ -9  -9 -11]]
[[2197 2161 2015]
 [2754 2695 2524]
 [2212 2171 2018]]
267.99999999999994
[[-0.50746269  0.23880597  0.2238806 ]
 [ 0.17910448 -0.23134328  0.12686567]
 [ 0.3358209   0.00373134 -0.32462687]]
3
